FROM node:14-alpine
LABEL Author Sagar Khan <sk.sagarkhan95@gmail.com>

# Additional Dependencies
RUN apk add bash --no-cache

# Set container timezone to IST
RUN apk --update add \
  bash \
  tzdata \
  && cp /usr/share/zoneinfo/Asia/Calcutta /etc/localtime \
  && echo /usr/share/zoneinfo/Asia/Calcutta > /etc/timezone \
  && apk del tzdata

# Create app directory
WORKDIR /opt/producer-service

# Install app dependencies
COPY package.json .
COPY package-lock.json .

RUN npm install

# Copy app source
COPY . .

# Compile application
RUN npm run build

ENTRYPOINT ["/bin/bash", "-c", "npm run start"]
